### Autograd

Central to all neural networks in PyTorch is the `autograd` package. Autograd is automatic differentiation, which allows for the backpropagation algorithm to work automatically, without explicitly writing down the gradients yourself. But unlike `tensorflow`, we can manipulate the gradients a lot more freely with `torch`.

In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


When we set `requires_grad=True` we start to track operations on it. Backpropagation requires us to know the computational history of the tensor.

In [3]:
y = x + 3
print(y)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)


In [4]:
y.grad_fn # as y was created from a tensor operation, it has a gradient!

In [5]:
z = y ** 2 + 1
w = torch.mean(z)
print("z = ", z)
print("w = ", w)

z =  tensor([[17., 17.],
        [17., 17.]], grad_fn=<AddBackward0>)
w =  tensor(17., grad_fn=<MeanBackward1>)


### Backpropagation

So now we can go backwards and use our gradient functions to help compute gradients.

In [6]:
w.backward() # this starts the backpropagation process
# this will fire an error if run twice

In [7]:
x.grad # this pulls out dw/dx

tensor([[2., 2.],
        [2., 2.]])

Okay, does this make any sense? Sure, if we compute the gradients by hand this is what we get.