These are my personal notes (Calvin Woo) on pytorch, following the pytorch blitz tutorial on `https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html`.

### Pytorch?

What is PyTorch? Why should I learn another framework... well, because apparently people use this a lot in the research space. Also because its supposibly simpler-- it's basically `numpy` but with CUDA. Sadly, I don't own an nVidia GPU (yet.) =(

In [1]:
import torch
import numpy as np

PyTorch, like literally everything, runs on tensors (though there are rumors of the terrible security of tensors, so we should use so-called *named tensors* ooooh.

In [2]:
torch.empty(5,3) # creates an unitialized tensor of dims 5-by-3. it's analogous to np.empty

tensor([[-5.8209e-03,  4.5761e-41, -5.8209e-03],
        [ 4.5761e-41,  1.7832e+25,  4.1906e-38],
        [ 7.1329e+25,  8.1413e-13,  1.1094e+27],
        [ 3.9285e+09,  4.8124e-38,  6.7003e-37],
        [ 4.5708e+27,  1.6900e+28,  6.7602e+28]])

In [3]:
np.empty((5,3)) # weirdly enough, they initialize with absurdly small values...

array([[2.86351437e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [4]:
x = torch.rand(5,3) # make random tensors
y = np.random.rand(5,3)
print("torch: ", x)
print("numpy: ", y)

torch:  tensor([[0.8590, 0.0403, 0.1278],
        [0.0300, 0.1903, 0.2185],
        [0.6671, 0.8325, 0.9415],
        [0.3203, 0.9969, 0.0351],
        [0.6110, 0.2400, 0.8261]])
numpy:  [[0.48665726 0.68455315 0.08259307]
 [0.31919208 0.63861245 0.58766955]
 [0.60985265 0.18576828 0.55926261]
 [0.16383985 0.31392393 0.02474209]
 [0.96914943 0.51125412 0.86356558]]


In [5]:
x = torch.zeros(5,3, dtype=torch.long) # so, the same thing?
y = np.zeros((5,3), dtype=np.int) # can also use np.long
print("torch: ", x)
print("numpy: ", y)

torch:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
numpy:  [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
x = torch.tensor([1,2,3])
y = np.array([1,2,3])
print("torch: ", x)
print("numpy: ", y)

torch:  tensor([1, 2, 3])
numpy:  [1 2 3]


At this point, it's pretty much `numpy`.

In [9]:
x = torch.rand(3,4)
y = x[1:]
print(y)

tensor([[0.9588, 0.2521, 0.5049, 0.7954],
        [0.0139, 0.1672, 0.8179, 0.6223]])


In [12]:
x.view(12)

tensor([0.2608, 0.1437, 0.3035, 0.5899, 0.9588, 0.2521, 0.5049, 0.7954, 0.0139,
        0.1672, 0.8179, 0.6223])

In [13]:
x = torch.randn(1) # .item() can pull out a number from a 1-element tensor
print(x)
print(x.item())

tensor([-1.4222])
-1.4221506118774414


In [15]:
x = torch.ones(2,3)
type(x)

torch.Tensor

In [17]:
y = x.numpy() # can convert a torch to numpy!
type(y)

numpy.ndarray

In [18]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
y = torch.from_numpy(x) # and back
y

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

So what's the point of `torch`? Well, it supports CUDA computation on a GPU.

In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to(device) # this is now a tensor on a CUDA device!

This allows seriously faster computation.